
// FIX: Correct the import path for types.
import type { Plant, Alert } from './types';

export const ALL_PLANTS: Plant[] = [
  // Original plants with corrected names
  {
    id: 'tomato-1',
    name: 'Tomato',
    species: 'Solanum lycopersicum',
    icon: '🍅',
    phenology: 'Fruiting',
    category: 'Vegetable',
  },
  {
    id: 'basil-1',
    name: 'Basil',
    species: 'Ocimum basilicum',
    icon: '🌿',
    phenology: 'Vegetative',
    category: 'Herb',
  },
  {
    id: 'zucchini-1',
    name: 'Zucchini',
    species: 'Cucurbita pepo',
    icon: '🥒',
    phenology: 'Flowering',
    category: 'Vegetable',
  },
  
  // Australia & New Zealand
  { id: 'alexandra-palm-1', name: 'Alexandra Palm', species: 'Archontophoenix alexandrae', icon: '🌴', phenology: 'Mature', category: 'Ornamental' },
  { id: 'aniseed-myrtle-1', name: 'Aniseed Myrtle', species: 'Syzygium anisatum', icon: '🌿', phenology: 'Mature', category: 'Herb' },
  { id: 'atherton-raspberry-1', name: 'Atherton Raspberry', species: 'Rubus probus', icon: '🍓', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'black-boy-1', name: 'Black Boy (Grass Tree)', species: 'Xanthorrhoea', icon: '🌳', phenology: 'Mature', category: 'Native' },
  { id: 'bunya-nut-1', name: 'Bunya Nut', species: 'Araucaria bidwillii', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'burdekin-plum-1', name: 'Burdekin Plum', species: 'Pleiogynium timoriense', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'candle-nut-1', name: 'Candle Nut', species: 'Aleurites moluccanus', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'cinnamon-myrtle-1', name: 'Cinnamon Myrtle', species: 'Backhousia myrtifolia', icon: '🌿', phenology: 'Mature', category: 'Herb' },
  { id: 'davidsons-plum-1', name: 'Davidson\'s Plum', species: 'Davidsonia pruriens', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'foxtail-palm-1', name: 'Foxtail Palm', species: 'Wodyetia bifurcata', icon: '🌴', phenology: 'Mature', category: 'Ornamental' },
  { id: 'native-yam-1', name: 'Native Yam (Ipomoea costata)', species: 'Ipomoea costata', icon: '🍠', phenology: 'Tuber', category: 'Root/Tuber' },
  { id: 'kentia-palm-1', name: 'Kentia Palm', species: 'Howea forsteriana', icon: '🌴', phenology: 'Mature', category: 'Ornamental' },
  { id: 'large-leaf-native-tamarind-1', name: 'Large Leaf Native Tamarind', species: 'Diploglottis australis', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'lemon-myrtle-1', name: 'Lemon Myrtle', species: 'Backhousia citriodora', icon: '🌿', phenology: 'Mature', category: 'Herb' },
  { id: 'lilly-pilly-1', name: 'Lilly Pilly', species: 'Syzygium smithii', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'macadamia-nut-1', name: 'Macadamia Nut', species: 'Macadamia integrifolia', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'native-tamarind-1', name: 'Native Tamarind (Small Leaved)', species: 'Diploglottis campbellii', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'peanut-tree-1', name: 'Peanut Tree', species: 'Sterculia quadrifida', icon: '🌳', phenology: 'Fruiting', category: 'Nut' },
  { id: 'sandpaper-fig-1', name: 'Sandpaper Fig', species: 'Ficus coronata', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'solitary-palm-1', name: 'Solitary Palm', species: 'Ptychosperma elegans', icon: '🌴', phenology: 'Mature', category: 'Ornamental' },
  { id: 'walking-stick-palm-1', name: 'Walking-stick Palm', species: 'Linospadix monostachyos', icon: '🌴', phenology: 'Mature', category: 'Ornamental' },
  { id: 'warrigal-greens-1', name: 'Warrigal Greens', species: 'Tetragonia tetragonioides', icon: '🥬', phenology: 'Vegetative', category: 'Vegetable' },
  { id: 'lemonade-1', name: 'Lemonade', species: 'Citrus limon x reticulata', icon: '🍋', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'oca-yam-1', name: 'Oca Yam', species: 'Oxalis tuberosa', icon: '🍠', phenology: 'Tuber', category: 'Root/Tuber' },

  // South American
  { id: 'abiu-1', name: 'Abiu', species: 'Pouteria caimito', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'achacha-1', name: 'Achacha', species: 'Garcinia humilis', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'achiote-1', name: 'Achiote', species: 'Bixa orellana', icon: '🌳', phenology: 'Fruiting', category: 'Spice' },
  { id: 'amaranth-1', name: 'Amaranth', species: 'Amaranthus', icon: '🥬', phenology: 'Vegetative', category: 'Vegetable' },
  { id: 'arrowroot-1', name: 'Arrowroot', species: 'Maranta arundinacea', icon: '🍠', phenology: 'Tuber', category: 'Root/Tuber' },
  { id: 'brazilian-cherry-1', name: 'Brazilian Cherry', species: 'Eugenia brasiliensis', icon: '🍒', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'cassava-1', name: 'Cassava', species: 'Manihot esculenta', icon: '🍠', phenology: 'Tuber', category: 'Root/Tuber' },
  { id: 'cherimoya-1', name: 'Cherimoya', species: 'Annona cherimola', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'feijoa-1', name: 'Feijoa', species: 'Acca sellowiana', icon: '🍈', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'grumichama-1', name: 'Grumichama', species: 'Eugenia brasiliensis', icon: '🍒', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'guava-1', name: 'Guava', species: 'Psidium guajava', icon: '🍈', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'ice-cream-bean-1', name: 'Ice-Cream Bean', species: 'Inga edulis', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'jaboticaba-1', name: 'Jaboticaba', species: 'Plinia cauliflora', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'madrono-1', name: 'Madrono', species: 'Garcinia madruno', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'passionfruit-1', name: 'Passionfruit', species: 'Passiflora edulis', icon: '🍈', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'pumpkin-1', name: 'Pumpkin', species: 'Cucurbita', icon: '🎃', phenology: 'Fruiting', category: 'Vegetable' },
  { id: 'rollinia-1', name: 'Rollinia', species: 'Annona mucosa', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },

  // North America, Mexico & Caribbean
  { id: 'acerola-cherry-1', name: 'Acerola Cherry', species: 'Malpighia emarginata', icon: '🍒', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'allspice-1', name: 'Allspice', species: 'Pimenta dioica', icon: '🌿', phenology: 'Mature', category: 'Spice' },
  { id: 'avocado-1', name: 'Avocado', species: 'Persea americana', icon: '🥑', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'black-sapote-1', name: 'Black Sapote', species: 'Diospyros nigra', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'canistel-1', name: 'Canistel', species: 'Pouteria campechiana', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'capulin-cherry-1', name: 'Capulin Cherry', species: 'Prunus salicifolia', icon: '🍒', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'chilli-1', name: 'Chilli', species: 'Capsicum annuum', icon: '🌶️', phenology: 'Fruiting', category: 'Vegetable' },
  { id: 'grapefruit-1', name: 'Grapefruit', species: 'Citrus × paradisi', icon: '🍊', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'hazelnut-1', name: 'Hazelnut', species: 'Corylus avellana', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'marigold-1', name: 'Marigold', species: 'Tagetes', icon: '🌼', phenology: 'Flowering', category: 'Ornamental' },
  { id: 'mountain-soursop-1', name: 'Mountain Soursop', species: 'Annona montana', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'pecan-nut-1', name: 'Pecan Nut', species: 'Carya illinoinensis', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'sapodilla-1', name: 'Sapodilla', species: 'Manilkara zapota', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'star-apple-1', name: 'Star Apple', species: 'Chrysophyllum cainito', icon: '🍎', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'white-sapote-1', name: 'White Sapote', species: 'Casimiroa edulis', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },

  // Asia and Indian Subcontinent
  { id: 'almond-1', name: 'Almond', species: 'Prunus dulcis', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'banana-1', name: 'Banana', species: 'Musa', icon: '🍌', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'betel-piper-1', name: 'Betel Piper', species: 'Piper betle', icon: '🌿', phenology: 'Vegetative', category: 'Herb' },
  { id: 'carambola-1', name: 'Carambola (Star Fruit)', species: 'Averrhoa carambola', icon: '🌟', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'cardamom-1', name: 'Cardamom', species: 'Elettaria cardamomum', icon: '🌿', phenology: 'Vegetative', category: 'Spice' },
  { id: 'cinnamon-1', name: 'Cinnamon', species: 'Cinnamomum verum', icon: '🌿', phenology: 'Mature', category: 'Spice' },
  { id: 'curry-leaf-1', name: 'Curry Leaf', species: 'Murraya koenigii', icon: '🌿', phenology: 'Mature', category: 'Herb' },
  { id: 'eggplant-1', name: 'Eggplant', species: 'Solanum melongena', icon: '🍆', phenology: 'Fruiting', category: 'Vegetable' },
  { id: 'galangal-1', name: 'Galangal', species: 'Alpinia galanga', icon: '🍠', phenology: 'Rhizome', category: 'Spice' },
  { id: 'ginger-1', name: 'Ginger', species: 'Zingiber officinale', icon: '🍠', phenology: 'Rhizome', category: 'Spice' },
  { id: 'jakfruit-1', name: 'Jakfruit', species: 'Artocarpus heterophyllus', icon: '🍈', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'jujube-1', name: 'Jujube', species: 'Ziziphus jujuba', icon: '🍎', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'kwai-muk-1', name: 'Kwai Muk', species: 'Artocarpus hypargyreus', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'lakoocha-1', name: 'Lakoocha', species: 'Artocarpus lacucha', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'lemon-1', name: 'Lemon', species: 'Citrus limon', icon: '🍋', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'lemongrass-1', name: 'Lemon Grass', species: 'Cymbopogon citratus', icon: '🌿', phenology: 'Vegetative', category: 'Herb' },
  { id: 'lime-1', name: 'Lime', species: 'Citrus aurantiifolia', icon: '🍋', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'longan-1', name: 'Longan', species: 'Dimocarpus longan', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'loquat-1', name: 'Loquat', species: 'Eriobotrya japonica', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'lychee-1', name: 'Lychee', species: 'Litchi chinensis', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'mandarin-1', name: 'Mandarin', species: 'Citrus reticulata', icon: '🍊', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'mango-1', name: 'Mango', species: 'Mangifera indica', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'mangosteen-1', name: 'Mangosteen', species: 'Garcinia mangostana', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'pandanus-1', name: 'Pandanus', species: 'Pandanus amaryllifolius', icon: '🌿', phenology: 'Vegetative', category: 'Herb' },
  { id: 'pepper-1', name: 'Pepper', species: 'Piper nigrum', icon: '🌿', phenology: 'Fruiting', category: 'Spice' },
  { id: 'pumelo-1', name: 'Pumelo', species: 'Citrus maxima', icon: '🍊', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'snake-beans-1', name: 'Snake Beans', species: 'Vigna unguiculata subsp. sesquipedalis', icon: '🥬', phenology: 'Fruiting', category: 'Vegetable' },
  { id: 'taro-1', name: 'Taro', species: 'Colocasia esculenta', icon: '🍠', phenology: 'Tuber', category: 'Root/Tuber' },
  { id: 'turmeric-1', name: 'Turmeric', species: 'Curcuma longa', icon: '🍠', phenology: 'Rhizome', category: 'Spice' },
  { id: 'wampee-1', name: 'Wampee', species: 'Clausena lansium', icon: '🥭', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'wax-gourd-1', name: 'Wax Gourd', species: 'Benincasa hispida', icon: '🍈', phenology: 'Fruiting', category: 'Vegetable' },

  // Middle East and Africa
  { id: 'aloe-vera-1', name: 'Aloe Vera', species: 'Aloe barbadensis miller', icon: '🌿', phenology: 'Vegetative', category: 'Medicinal' },
  { id: 'apple-1', name: 'Apple', species: 'Malus domestica', icon: '🍎', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'bottle-gourd-1', name: 'Bottle Gourd', species: 'Lagenaria siceraria', icon: '🍈', phenology: 'Fruiting', category: 'Vegetable' },
  { id: 'coffee-1', name: 'Coffee', species: 'Coffea arabica', icon: '☕', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'date-1', name: 'Date Palm', species: 'Phoenix dactylifera', icon: '🌴', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'okra-1', name: 'Okra', species: 'Abelmoschus esculentus', icon: '🥬', phenology: 'Fruiting', category: 'Vegetable' },
  { id: 'olive-1', name: 'Olive', species: 'Olea europaea', icon: '🫒', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'pomegranate-1', name: 'Pomegranate', species: 'Punica granatum', icon: '🍎', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'rosella-1', name: 'Rosella', species: 'Hibiscus sabdariffa', icon: '🌺', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'walnut-1', name: 'Walnut', species: 'Juglans regia', icon: '🌰', phenology: 'Fruiting', category: 'Nut' },
  { id: 'watermelon-1', name: 'Watermelon', species: 'Citrullus lanatus', icon: '🍉', phenology: 'Fruiting', category: 'Fruit' },

  // Mediterranean and Europe
  { id: 'bay-tree-1', name: 'Bay Tree', species: 'Laurus nobilis', icon: '🌿', phenology: 'Mature', category: 'Herb' },
  { id: 'fig-1', name: 'Fig', species: 'Ficus carica', icon: '🌳', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'pear-1', name: 'Pear', species: 'Pyrus', icon: '🍐', phenology: 'Fruiting', category: 'Fruit' },
  { id: 'quince-1', name: 'Quince', species: 'Cydonia oblonga', icon: '🍎', phenology: 'Fruiting', category: 'Fruit' },
];

export const HEATWAVE_ALERT: Alert = {
    id: 'alert-1',
    title: 'Heatwave Warning!',
    message: 'Extreme heat is forecast for the next few days. Ensure plants are well-hydrated and consider providing shade.',
    severity: 'Critical',
};